<html>

<head>
    <title>Hello world</title>
</head>

<body>
    <?php
    include 'EJERCICIO2-devuelve-PARTE12.php';
    cabecera();
    ?>
    <h2>Bienvenido</h2>
    <a href="EJERCICIO2-subpagina1-PARTE12.php">Ir a página 1</a> <br>
    <a href="EJERCICIO2-subpagina2-PARTE12.php">Ir a página 2</a> <br>
    <a href="EJERCICIO2-subpagina3-PARTE12.php">Ir a página 3</a> <br>
    <?php
    pie();
    ?>
</body>

</html>